### ISSUE TITLE
Composer installation method is outdated

### ISSUE THREAD

**Issue by fabriziofs** [CodelyTV/php-basic-skeleton#32]
The available version of this skeleton on Packagist is the **1.2.1**(_18/07/2018_) and it's not compatible with PHP 8.

Maybe it's a good idea to create a new release for keep the support of  `composer create-project codelytv/php-bootstrap your-project-name` method?

Thanks! <💚>

**Comment by abel-santos-corral** [comment]
For me it's running with this:
`composer create-project --ignore-platform-reqs  codelytv/php-bootstrap tdd`

**Comment by rgomezcasas** [comment]
This should be working with the latest php version 🙌
